feat: migrate to 3.0
jina-ai/executor-faiss-postgres pull request #1
Opened 2022-02-28 03:59 UTC by winstonww

Diff: https://github.com/jina-ai/executors/pull/323

A workaround is introduced to make matches' ids unique, but this should be removed once issue is addressed.

2022-03-01 07:59 UTC, winstonww commented on .pre-commit-config.yaml
> +        #   - repo: https://github.com/pycqa/flake8
this is commented out now to generate diff but will enable this before merging

2022-04-04 05:32 UTC, nan-wang commented on manifest.yml
> +url: https://github.com/jina-ai/executors/tree/main/jinahub/indexers/compound/FaissPostgresIndexer
please update this url

2022-04-06 02:06 UTC, numb3r3 requested changes

2022-04-06 02:06 UTC, numb3r3 commented on Dockerfile
> +FROM jinaai/jina:2-py37-perf as base
use jina 3 base image.

2022-04-06 02:06 UTC, numb3r3 commented on Dockerfile
> +RUN apt-get update && apt-get install -y git
`git` can be removed here.

2022-04-06 02:06 UTC, numb3r3 commented on config.yml
> +  name: faiss_postgres_searcher
check the above args

2022-04-06 02:06 UTC, numb3r3 commented on .pre-commit-config.yaml
> +        #   - repo: https://github.com/pycqa/flake8
you can borrow some code from docarray, finetuner etc.,

2022-07-27 05:46 UTC, nan-wang commented
Close the PR because there is no updates for quite a while.

2022-07-27 05:46 UTC, closed without merging